import React, { useState, useEffect, useCallback } from 'react';
import {
  trainModel, evaluateModel, getModelStatus, getDatasetStats, runDemoScenario,
} from '../api/client';

interface EvalResults {
  n_test_samples: number;
  n_compatible: number;
  n_conflict: number;
  baseline: {
    accuracy: number; precision: number; recall: number; f1: number;
    confusion_matrix: number[][]; false_positives: number; false_negatives: number;
    avg_classification_time_ms: number;
  };
  ml_classifier: {
    accuracy: number; precision: number; recall: number; f1: number;
    confusion_matrix: number[][]; false_positives: number; false_negatives: number;
    avg_classification_time_ms: number;
  };
}

interface ModelStatus {
  trained: boolean;
  results: {
    algorithm: string; n_samples: number; n_train: number; n_test: number;
    n_compatible: number; n_conflict: number; training_time_s: number;
    accuracy: number; precision: number; recall: number; f1: number;
    confusion_matrix: number[][]; features: string[];
  } | null;
}

interface DatasetStats {
  exists: boolean;
  n_samples?: number; n_compatible?: number; n_conflict?: number; features?: string[];
}

function Metric({ label, val, better, worse }: { label: string; val: number | string; better?: boolean; worse?: boolean }) {
  return (
    <div className="metric-row">
      <span className="metric-name">{label}</span>
      <span
        className="metric-val"
        style={{
          color: better ? 'var(--green)' : worse ? 'var(--red)' : 'var(--accent)',
        }}
      >
        {typeof val === 'number' ? (val > 1 ? val.toFixed(1) : (val * 100).toFixed(1) + '%') : val}
      </span>
    </div>
  );
}

function ConfusionMatrix({ cm }: { cm: number[][] }) {
  if (!cm || cm.length < 2) return null;
  const [[tn, fp], [fn, tp]] = cm;
  return (
    <div className="confusion-matrix" style={{ marginTop: 8 }}>
      <div className="cm-cell tp">
        <div className="cm-val">{tp}</div>
        <div className="cm-label">True Positive</div>
      </div>
      <div className="cm-cell fp">
        <div className="cm-val">{fp}</div>
        <div className="cm-label">False Positive</div>
      </div>
      <div className="cm-cell fn">
        <div className="cm-val">{fn}</div>
        <div className="cm-label">False Negative</div>
      </div>
      <div className="cm-cell tn">
        <div className="cm-val">{tn}</div>
        <div className="cm-label">True Negative</div>
      </div>
    </div>
  );
}

export const ResearchDashboard: React.FC = () => {
  const [modelStatus, setModelStatus] = useState<ModelStatus>({ trained: false, results: null });
  const [datasetStats, setDatasetStats] = useState<DatasetStats>({ exists: false });
  const [evalResults, setEvalResults] = useState<EvalResults | null>(null);
  const [demoResult, setDemoResult] = useState<any>(null);
  const [algorithm, setAlgorithm] = useState('random_forest');
  const [nSamples, setNSamples] = useState(800);
  const [loading, setLoading] = useState<string | null>(null);
  const [error, setError] = useState('');

  const refresh = useCallback(async () => {
    try {
      const [ms, ds] = await Promise.all([getModelStatus(), getDatasetStats()]);
      setModelStatus(ms);
      setDatasetStats(ds);
    } catch {
      setError('Could not reach Python service. Make sure it is running on port 8000.');
    }
  }, []);

  useEffect(() => { refresh(); }, [refresh]);

  const handleTrain = async () => {
    setLoading('Training model…');
    setError('');
    try {
      await trainModel(algorithm, nSamples);
      await refresh();
    } catch (e: any) {
      setError(e.message);
    } finally {
      setLoading(null);
    }
  };

  const handleEvaluate = async () => {
    setLoading('Running evaluation…');
    setError('');
    try {
      const res = await evaluateModel();
      setEvalResults(res.evaluation);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setLoading(null);
    }
  };

  const handleDemo = async (scenario: 'compatible' | 'conflict') => {
    setLoading(`Running ${scenario} demo…`);
    setError('');
    try {
      const res = await runDemoScenario(scenario);
      setDemoResult(res);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setLoading(null);
    }
  };

  const r = modelStatus.results;
  const ev = evalResults;

  return (
    <div className="research-page">
      {loading && <div className="loading-bar" />}

      {/* Header */}
      <div className="research-header">
        <div>
          <h2>Research Evaluation Dashboard</h2>
          <p>
            Evaluate the ML-assisted AST-aware conflict classifier against a rule-based baseline.
            All metrics are generated by running actual experiments on the synthetic dataset.
          </p>
        </div>
        <div style={{ display: 'flex', gap: 8, flexShrink: 0 }}>
          <button className="btn btn-secondary btn-sm" onClick={refresh} disabled={!!loading}>
            ↻ Refresh
          </button>
        </div>
      </div>

      {error && (
        <div style={{ padding: '10px 14px', background: 'var(--red-dim)', border: '1px solid rgba(248,113,113,0.3)', borderRadius: 'var(--radius-md)', color: 'var(--red)', fontSize: 13, marginBottom: 16 }}>
          {error}
        </div>
      )}

      {/* Training Controls */}
      <div className="demo-scenario-section" style={{ marginBottom: 20 }}>
        <h3>⚙ Step 1 — Train the ML Classifier</h3>
        <p>
          Generate a synthetic dataset of concurrent Python edit pairs (compatible + conflict), then train a classifier.
          This is a prototype dataset — see the research documentation for limitations.
        </p>
        <div style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' }}>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
            <label style={{ fontSize: 11, color: 'var(--text-muted)', fontWeight: 600, letterSpacing: '0.05em', textTransform: 'uppercase' }}>Algorithm</label>
            <select
              value={algorithm}
              onChange={(e) => setAlgorithm(e.target.value)}
              style={{ background: 'var(--bg-base)', border: '1px solid var(--border)', color: 'var(--text-primary)', borderRadius: 'var(--radius-sm)', padding: '6px 10px', fontSize: 13, outline: 'none' }}
            >
              <option value="random_forest">Random Forest</option>
              <option value="logistic_regression">Logistic Regression</option>
              <option value="gradient_boosting">Gradient Boosting</option>
            </select>
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
            <label style={{ fontSize: 11, color: 'var(--text-muted)', fontWeight: 600, letterSpacing: '0.05em', textTransform: 'uppercase' }}>Samples</label>
            <select
              value={nSamples}
              onChange={(e) => setNSamples(Number(e.target.value))}
              style={{ background: 'var(--bg-base)', border: '1px solid var(--border)', color: 'var(--text-primary)', borderRadius: 'var(--radius-sm)', padding: '6px 10px', fontSize: 13, outline: 'none' }}
            >
              <option value={200}>200</option>
              <option value={400}>400</option>
              <option value={800}>800</option>
              <option value={1600}>1600</option>
            </select>
          </div>
          <button
            className="btn btn-primary"
            style={{ marginTop: 16 }}
            onClick={handleTrain}
            disabled={!!loading}
          >
            {loading === 'Training model…' ? <><span className="spinner" /> Training…</> : '▶ Generate Dataset &amp; Train'}
          </button>
          {modelStatus.trained && (
            <button
              className="btn btn-secondary"
              style={{ marginTop: 16 }}
              onClick={handleEvaluate}
              disabled={!!loading}
            >
              {loading === 'Running evaluation…' ? <><span className="spinner" /> Evaluating…</> : '📊 Run Full Evaluation'}
            </button>
          )}
        </div>
      </div>

      {/* Metrics Grid */}
      <div className="research-grid">
        {/* Dataset */}
        <div className="research-card">
          <div className="research-card-title">
            <span className="icon">📦</span> Dataset
          </div>
          {datasetStats.exists ? (
            <>
              <div className="big-stat">{datasetStats.n_samples?.toLocaleString()}</div>
              <div className="big-stat-label">Total samples</div>
              <div style={{ marginTop: 12 }}>
                <Metric label="Compatible (label=0)" val={datasetStats.n_compatible ?? 0} />
                <Metric label="Conflict (label=1)" val={datasetStats.n_conflict ?? 0} />
                <Metric label="Train/Test split" val="80 / 20" />
                <Metric label="Features" val={datasetStats.features?.length ?? 12} />
              </div>
              <div style={{ marginTop: 8, padding: '6px 8px', background: 'var(--bg-base)', borderRadius: 'var(--radius-sm)', fontSize: 10, color: 'var(--text-muted)', lineHeight: 1.6 }}>
                ⚠ Synthetic prototype dataset. See docs/research.md for limitations.
              </div>
            </>
          ) : (
            <div className="empty-state">
              <div>No dataset yet.</div>
              <div>Train the model to generate one.</div>
            </div>
          )}
        </div>

        {/* Model Info */}
        <div className="research-card">
          <div className="research-card-title">
            <span className="icon">🤖</span> Model
          </div>
          {r ? (
            <>
              <div className="big-stat">{r.accuracy > 0 ? (r.accuracy * 100).toFixed(1) + '%' : '—'}</div>
              <div className="big-stat-label">Accuracy on test set</div>
              <div style={{ marginTop: 12 }}>
                <Metric label="Algorithm" val={r.algorithm.replace('_', ' ')} />
                <Metric label="Training samples" val={r.n_train} />
                <Metric label="Test samples" val={r.n_test} />
                <Metric label="Training time" val={r.training_time_s + 's'} />
              </div>
              <ConfusionMatrix cm={r.confusion_matrix} />
            </>
          ) : (
            <div className="empty-state">
              <div>Model not trained.</div>
              <div>Run Step 1 above.</div>
            </div>
          )}
        </div>

        {/* ML Results */}
        <div className="research-card">
          <div className="research-card-title">
            <span className="icon">📈</span> ML Classifier Results
          </div>
          {ev ? (
            <>
              <Metric label="Accuracy" val={ev.ml_classifier.accuracy} better={ev.ml_classifier.accuracy > ev.baseline.accuracy} />
              <Metric label="Precision" val={ev.ml_classifier.precision} better={ev.ml_classifier.precision > ev.baseline.precision} />
              <Metric label="Recall" val={ev.ml_classifier.recall} better={ev.ml_classifier.recall > ev.baseline.recall} />
              <Metric label="F1-Score" val={ev.ml_classifier.f1} better={ev.ml_classifier.f1 > ev.baseline.f1} />
              <Metric label="False Positives" val={ev.ml_classifier.false_positives} worse={ev.ml_classifier.false_positives > ev.baseline.false_positives} />
              <Metric label="False Negatives" val={ev.ml_classifier.false_negatives} worse={ev.ml_classifier.false_negatives > ev.baseline.false_negatives} />
              <Metric label="Avg. Classification Time" val={ev.ml_classifier.avg_classification_time_ms.toFixed(3) + ' ms'} />
              <ConfusionMatrix cm={ev.ml_classifier.confusion_matrix} />
            </>
          ) : r ? (
            <>
              <Metric label="Accuracy" val={r.accuracy} />
              <Metric label="Precision" val={r.precision} />
              <Metric label="Recall" val={r.recall} />
              <Metric label="F1-Score" val={r.f1} />
              <div style={{ marginTop: 8, fontSize: 11, color: 'var(--text-muted)' }}>
                Run full evaluation to compare against baseline.
              </div>
              <ConfusionMatrix cm={r.confusion_matrix} />
            </>
          ) : (
            <div className="empty-state">Train model first.</div>
          )}
        </div>
      </div>

      {/* Baseline Comparison Table */}
      {ev && (
        <div className="research-card" style={{ marginBottom: 20 }}>
          <div className="research-card-title">
            <span className="icon">⚡</span> Baseline vs ML Classifier — Full Comparison
          </div>
          <div style={{ marginBottom: 8, fontSize: 11, color: 'var(--text-muted)', lineHeight: 1.6 }}>
            <strong>Baseline:</strong> Rule-based detector using line-range overlap + same-name heuristics (text/position-based). &nbsp;
            <strong>ML Classifier:</strong> AST feature extraction + {r?.algorithm?.replace('_', ' ') ?? 'classifier'} trained on synthetic dataset.
            Results are measured on the held-out test split ({ev.n_test_samples} samples).
          </div>
          <table className="comparison-table">
            <thead>
              <tr>
                <th>Metric</th>
                <th>Baseline (Rule-Based)</th>
                <th>ML Classifier (AST + ML)</th>
                <th>Δ</th>
              </tr>
            </thead>
            <tbody>
              {(['accuracy', 'precision', 'recall', 'f1'] as const).map((m) => {
                const bVal = ev.baseline[m];
                const mVal = ev.ml_classifier[m];
                const delta = mVal - bVal;
                return (
                  <tr key={m}>
                    <td style={{ color: 'var(--text-primary)', fontFamily: 'Inter' }}>
                      {m.charAt(0).toUpperCase() + m.slice(1)}
                    </td>
                    <td className={bVal >= mVal ? 'better' : 'worse'}>
                      {(bVal * 100).toFixed(2)}%
                    </td>
                    <td className={mVal >= bVal ? 'better' : 'worse'}>
                      {(mVal * 100).toFixed(2)}%
                    </td>
                    <td style={{ color: delta >= 0 ? 'var(--green)' : 'var(--red)', fontFamily: 'JetBrains Mono' }}>
                      {delta >= 0 ? '+' : ''}{(delta * 100).toFixed(2)}%
                    </td>
                  </tr>
                );
              })}
              <tr>
                <td style={{ color: 'var(--text-primary)', fontFamily: 'Inter' }}>False Positives</td>
                <td className={ev.baseline.false_positives <= ev.ml_classifier.false_positives ? 'better' : 'worse'}>
                  {ev.baseline.false_positives}
                </td>
                <td className={ev.ml_classifier.false_positives <= ev.baseline.false_positives ? 'better' : 'worse'}>
                  {ev.ml_classifier.false_positives}
                </td>
                <td style={{ color: ev.ml_classifier.false_positives <= ev.baseline.false_positives ? 'var(--green)' : 'var(--red)', fontFamily: 'JetBrains Mono' }}>
                  {ev.ml_classifier.false_positives - ev.baseline.false_positives >= 0 ? '+' : ''}
                  {ev.ml_classifier.false_positives - ev.baseline.false_positives}
                </td>
              </tr>
              <tr>
                <td style={{ color: 'var(--text-primary)', fontFamily: 'Inter' }}>False Negatives</td>
                <td className={ev.baseline.false_negatives <= ev.ml_classifier.false_negatives ? 'better' : 'worse'}>
                  {ev.baseline.false_negatives}
                </td>
                <td className={ev.ml_classifier.false_negatives <= ev.baseline.false_negatives ? 'better' : 'worse'}>
                  {ev.ml_classifier.false_negatives}
                </td>
                <td style={{ color: ev.ml_classifier.false_negatives <= ev.baseline.false_negatives ? 'var(--green)' : 'var(--red)', fontFamily: 'JetBrains Mono' }}>
                  {ev.ml_classifier.false_negatives - ev.baseline.false_negatives >= 0 ? '+' : ''}
                  {ev.ml_classifier.false_negatives - ev.baseline.false_negatives}
                </td>
              </tr>
              <tr>
                <td style={{ color: 'var(--text-primary)', fontFamily: 'Inter' }}>Avg. Classification Time</td>
                <td style={{ fontFamily: 'JetBrains Mono', color: 'var(--text-secondary)' }}>
                  {ev.baseline.avg_classification_time_ms.toFixed(3)} ms
                </td>
                <td style={{ fontFamily: 'JetBrains Mono', color: 'var(--text-secondary)' }}>
                  {ev.ml_classifier.avg_classification_time_ms.toFixed(3)} ms
                </td>
                <td style={{ fontFamily: 'JetBrains Mono', color: 'var(--text-muted)' }}>—</td>
              </tr>
            </tbody>
          </table>
        </div>
      )}

      {/* Demo Scenarios */}
      <div className="demo-scenario-section">
        <h3>🔬 Step 2 — Run Demo Scenarios</h3>
        <p>
          Demonstrate the ML pipeline with pre-built scenarios. The Python AST service will parse,
          extract features, and classify the concurrent changes.
        </p>
        <div className="demo-scenarios">
          <div className="scenario-card" onClick={() => handleDemo('compatible')}>
            <h4>
              <span className="badge badge-compatible" style={{ marginRight: 8 }}>Compatible</span>
              Independent Functions
            </h4>
            <pre>{`User A: modify calculate() → return x * 3
User B: add validate(x) → return x > 0

Expected: These affect DIFFERENT AST nodes → Compatible`}</pre>
          </div>
          <div className="scenario-card" onClick={() => handleDemo('conflict')}>
            <h4>
              <span className="badge badge-conflict" style={{ marginRight: 8 }}>Conflict</span>
              Same Function
            </h4>
            <pre>{`User A: modify calculate() → return x * 3
User B: modify calculate() → return x + 10

Expected: SAME FunctionDef node → Potential Conflict`}</pre>
          </div>
        </div>

        {demoResult && (
          <div style={{ marginTop: 14, padding: 14, background: 'var(--bg-elevated)', border: '1px solid var(--border)', borderRadius: 'var(--radius-md)' }}>
            <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.06em', textTransform: 'uppercase', color: 'var(--text-muted)', marginBottom: 8 }}>
              Demo Result — {demoResult.scenario}
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 12, fontSize: 12 }}>
              <div>
                <div style={{ color: 'var(--text-muted)', marginBottom: 4 }}>Change A</div>
                <div style={{ fontFamily: 'JetBrains Mono', fontSize: 11 }}>
                  {demoResult.change_a?.operation} {demoResult.change_a?.node_type} "{demoResult.change_a?.name}"
                </div>
              </div>
              <div>
                <div style={{ color: 'var(--text-muted)', marginBottom: 4 }}>Change B</div>
                <div style={{ fontFamily: 'JetBrains Mono', fontSize: 11 }}>
                  {demoResult.change_b?.operation} {demoResult.change_b?.node_type} "{demoResult.change_b?.name}"
                </div>
              </div>
              <div>
                <div style={{ color: 'var(--text-muted)', marginBottom: 4 }}>ML Prediction</div>
                <span
                  className={`badge ${demoResult.prediction?.label === 0 ? 'badge-compatible' : 'badge-conflict'}`}
                >
                  {demoResult.prediction?.prediction}
                </span>
                <div style={{ color: 'var(--text-muted)', marginTop: 4, fontFamily: 'JetBrains Mono', fontSize: 11 }}>
                  {demoResult.prediction?.confidence !== undefined
                    ? (demoResult.prediction.confidence * 100).toFixed(1) + '% confidence'
                    : ''}
                </div>
              </div>
            </div>
            {demoResult.prediction?.explanation && (
              <div style={{ marginTop: 8, fontSize: 11, color: 'var(--text-secondary)', fontStyle: 'italic' }}>
                {demoResult.prediction.explanation}
              </div>
            )}
          </div>
        )}
      </div>

      {/* Research Framing */}
      <div className="research-card" style={{ marginTop: 20 }}>
        <div className="research-card-title">
          <span className="icon">📄</span> Research Context
        </div>
        <div style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.7 }}>
          <p style={{ marginBottom: 10 }}>
            <strong style={{ color: 'var(--text-primary)' }}>Research Gap:</strong> Existing collaborative code-editing systems can synchronize concurrent textual changes using CRDTs, while AST-based approaches provide structural information. However, the use of machine learning to classify whether concurrent AST-level code changes are structurally compatible or conflicting within a local-first CRDT environment remains insufficiently explored.
          </p>
          <p style={{ marginBottom: 10 }}>
            <strong style={{ color: 'var(--text-primary)' }}>Research Question:</strong> Can an ML classifier trained on AST structural features meaningfully improve the detection of concurrent code conflicts compared to text/position-based heuristics?
          </p>
          <p style={{ marginBottom: 10 }}>
            <strong style={{ color: 'var(--text-primary)' }}>Hypothesis:</strong> AST-level structural features (node type, name, operation combination, line overlap) provide sufficient discriminatory signal for an ML model to outperform a rule-based baseline in classifying concurrent code changes.
          </p>
          <p style={{ color: 'var(--text-muted)', fontSize: 11 }}>
            ⚠ This is a prototype. The dataset is synthetic and generated for demonstration purposes. Results should not be extrapolated to real-world codebases without further validation on real concurrent edit logs.
          </p>
        </div>
      </div>
    </div>
  );
};
